#!/bin/bash
r="$1"
r="${r//_EX_/!}"
r="${r//_DL_/\$}"
r="${r//_MD_/%}"
r="${r//_AM_/&}"
r="${r//_ML_/*}"
r="${r//_AD_/+}"
r="${r//_SB_/-}"
r="${r//_DT_/.}"
r="${r//_DV_/\/}"
r="${r//_CL_/:}"
r="${r//_SC_/;}"
r="${r//_LT_/<}"
r="${r//_EQ_/=}"
r="${r//_GT_/>}"
r="${r//_QM_/?}"
r="${r//_AT_/@}"
r="${r//_LB_/\[}"
r="${r//_RB_/\]}"
r="${r//_HT_/^}"
r="${r//_US_/_}"
r="${r//_TK_/\`}"
r="${r//_BR_/|}"
r="${r//_TL_/~}"
echo "" | awk 'END { s = "'"$r"'";
    righti = -1;
    for (i = 0; i < length(s); i ++) {
        if (substr(s,i,1) == ":") {
            i ++;
            if (substr(s,i,1) != ":") {
                righti = i;
            }
        }
    }

    if (righti == -1) {
        print s;
    } else {
        right = substr(s, righti, length(s)-righti+1);
        left = substr(s, 0, righti - 2);
        print left "\t" right;
    }
}'
